# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DealApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  use_modular_headers!

  pod 'R.swift'
#  pod 'RealmSwift'
  pod 'Moya'
  pod 'Firebase/Analytics'
  pod 'FirebaseCore'
  pod 'FirebaseFirestore'
  pod 'FirebaseMessaging'
#  pod 'Firebase/Crashlytics'
  pod 'SDWebImage'
  pod 'SVProgressHUD'
  pod 'IQKeyboardManagerSwift'
  pod 'RNCryptor', '~> 5.0'
  pod 'KeychainSwift', '~> 19.0'
  pod 'DropDown'
  pod 'FSCalendar'
  pod "Popover"
  pod 'BRYXBanner'
  # Pods for DealApp
end

target 'ImageNotification' do
  use_frameworks!
  pod 'FirebaseMessaging'
end
